name: Datadog Logging Setup

on:
  workflow_dispatch: # manually triggerable

jobs:
  heroku-datadog-setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Install Heroku CLI (multi-command, use `run: |`)
      - name: Install Heroku CLI
        run: run: curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku (single command, use `run:`)
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # Add Datadog log drain 
      - name: Add Datadog log drain
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          # Add the Datadog log drain to Heroku
          heroku drains:add \
            "https://http-intake.logs.datadoghq.eu/v1/input/${DATADOG_API_KEY}?ddsource=heroku&service=battlesnake" \
            --app $HEROKU_APP_NAME || echo "Drain already exists"
